java_test(
    name = "rulesjvmrelocateddeps",
    srcs = ["RulesJvmRelocatedDepsTest.java"],
    test_class = "se.mandrean.rulesjvmrelocateddeps.RulesJvmRelocatedDepsTest",
    deps = [
        "@maven//:junit_junit",
        #"@maven//:commons_io_commons_io",
        "@maven//:org_apache_commons_commons_io",
    ],
)
